version: '3.7'
services:
  backend:
    ports: 
      - '4001:4001'
    build: ./backend
  mysql:
    image: mysql:8
    volumes:
      - storage:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
  frontend:
    ports: 
      - '4000:4000'
    build: ./frontend    
volumes:
  storage:


    