version: '3.7'
services:
  backend:
    ports: 
      - '4001:4001'
    build: ./backend
  mysql:
    image: mysql:8
    volumes:
      - storage10:/var/lib/mysql
    env_file:
      - .env
  frontend:
    ports: 
      - '4000:4000'
    build: ./frontend    
volumes:
  storage10: